import SwiftUI

struct CommentatorView: View {
    @EnvironmentObject var vm: CommentatorViewModel
    @EnvironmentObject var match: MatchCenterViewModel
    var body: some View { VStack(spacing: 0) { ScrollViewReader { proxy in ScrollView { LazyVStack(spacing: 16) { if vm.messages.isEmpty { ScreenStateView(title: "Ask about the selected match.", subtitle: match.fixture == nil ? "Select a live match first. The AI will never invent missing football data." : "Answers use only the match data shown in Match Center.", systemImage: "bubble.left.and.text.bubble.right") }; ForEach(vm.messages) { AIChatBubble(message: $0).id($0.id) }; if vm.isLoading { ProgressView().tint(AppColors.lime) }; if let error = vm.errorMessage { Text(error).foregroundColor(AppColors.red).font(.system(size: 11)) } }.padding(24) }.onChange(of: vm.messages.count) { _, _ in if let id = vm.messages.last?.id { withAnimation { proxy.scrollTo(id, anchor: .bottom) } } } }; Divider().overlay(AppColors.border); composer }.background(AppColors.bg) }
    private var composer: some View { VStack(alignment: .leading, spacing: 10) { ScrollView(.horizontal, showsIndicators: false) { HStack { ForEach(vm.chips, id: \.self) { chip in Button { Task { await vm.send(chip, fixture: match.fixture, statistics: match.statistics, events: match.events) } } label: { Text(chip).font(.system(size: 9)).foregroundColor(AppColors.muted).padding(.horizontal, 10).padding(.vertical, 5).overlay(Capsule().stroke(AppColors.border)) }.buttonStyle(.plain) } } }; HStack(alignment: .bottom) { TextEditor(text: $vm.input).font(.system(size: 11)).scrollContentBackground(.hidden).frame(minHeight: 36, maxHeight: 90); Button("Clear") { vm.clear() }.buttonStyle(.plain).foregroundColor(AppColors.muted); Button { Task { await vm.send(fixture: match.fixture, statistics: match.statistics, events: match.events) } } label: { Image(systemName: "arrow.up.right").foregroundColor(.black).frame(width: 26, height: 26).background(Circle().fill(AppColors.lime)) }.buttonStyle(.plain).disabled(vm.isLoading) }.padding(10).background(AppColors.card).clipShape(RoundedRectangle(cornerRadius: 10)).overlay(RoundedRectangle(cornerRadius: 10).stroke(AppColors.border)) }.padding(20) }
}
struct AIChatBubble: View { let message: ChatMessage; var body: some View { HStack { if message.isUser { Spacer() }; Text(message.text.joined(separator: "\n\n")).font(.system(size: 11)).foregroundColor(message.isUser ? .black : AppColors.text).padding(14).background(message.isUser ? AppColors.lime : AppColors.card).clipShape(RoundedRectangle(cornerRadius: 14)).frame(maxWidth: 620, alignment: message.isUser ? .trailing : .leading); if !message.isUser { Spacer() } } } }
